#!/usr/bin/env python3
"""Refresh the vendored, pinned copy of the role claim register. AAASM-5763.

WHY THIS EXISTS
---------------
`check-register-drift.py` (AAASM-5587) already diffs the built site against
`docs/src/role-narratives.md`, but by default it either fetches that file
live over HTTPS at CI time (network dependency: a merge in `docs` can turn
this repo's CI red with nobody touching this repo) or takes a local path (no
CI use at all, since nothing in this repo's checkout ships `docs`). Neither
option is wired into CI (AAASM-5587 PR #99 weighed exactly these two and
deferred). AAASM-5763 adds the third shape PR #99 named but didn't build: a
**generated, pinned artifact**, matching the `capability-surface.toml`
precedent (`docs/scripts/extract_capability_surface.py`, AAASM-5531/5609) --
a committed projection carrying the exact upstream commit it was taken from,
regenerated by hand when the upstream page changes, read with zero network
access in CI.

Unlike the capability manifest's case, the source here (`role-narratives.md`)
is already the exact Markdown format `check-register-drift.py` parses -- no
format transformation is needed, so this script is a straight copy plus a pin
comment, not an extraction into a new schema.

DIVISION OF LABOUR
------------------
* This script needs a sibling `docs` checkout and is **not** run in CI --
  same reasoning as `extract_capability_surface.py`.
* `check-register-drift.py --register vendor/role-narratives.md` reads only
  the committed file and **is** run in CI, with zero network access.
* Proving the vendored copy still matches the *live* upstream page is a
  separate, still-not-CI concern -- see `check-role-register-upstream.py`.

Usage:
    python3 scripts/sync-role-register.py \
        --docs-checkout ../docs \
        --source-commit <40-hex sha of the docs commit read>
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

PIN_MARKER_START = "<!-- PIN:role-register:BEGIN -->"
PIN_MARKER_END = "<!-- PIN:role-register:END -->"
VENDOR_PATH = pathlib.Path(__file__).resolve().parent.parent / "vendor" / "role-narratives.md"


def build_pin_block(source_commit: str) -> str:
    return (
        f"{PIN_MARKER_START}\n"
        "<!--\n"
        "  GENERATED FILE -- do not hand-edit.\n"
        "  A pinned projection of docs/src/role-narratives.md (AAASM-5763), matching\n"
        "  the capability-surface.toml precedent (AAASM-5531/5609): a committed copy\n"
        "  carrying the exact upstream commit it was taken from, so CI can validate\n"
        "  against it with zero network access. Regenerate with:\n"
        "    python3 scripts/sync-role-register.py --docs-checkout <path> --source-commit <sha>\n"
        "  Proving this pin still matches the LIVE upstream page is a separate,\n"
        "  still-not-CI check -- see check-role-register-upstream.py.\n\n"
        "  source_repository: ai-agent-assembly/docs\n"
        "  source_path: docs/src/role-narratives.md\n"
        f"  source_commit: {source_commit}\n"
        "-->\n"
        f"{PIN_MARKER_END}\n\n"
    )


def strip_existing_pin(text: str) -> str:
    pattern = re.compile(
        re.escape(PIN_MARKER_START) + r".*?" + re.escape(PIN_MARKER_END) + r"\n*",
        re.DOTALL,
    )
    return pattern.sub("", text, count=1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--docs-checkout", required=True, help="path to a docs repo checkout")
    ap.add_argument("--source-commit", required=True, help="40-hex sha of the docs commit read")
    args = ap.parse_args()

    if not re.fullmatch(r"[0-9a-f]{40}", args.source_commit):
        print(f"--source-commit must be a 40-hex sha, got {args.source_commit!r}", file=sys.stderr)
        return 1

    source_path = pathlib.Path(args.docs_checkout).expanduser().resolve() / "docs" / "src" / "role-narratives.md"
    if not source_path.is_file():
        print(f"no such file: {source_path}", file=sys.stderr)
        return 1

    body = strip_existing_pin(source_path.read_text(encoding="utf-8"))
    VENDOR_PATH.parent.mkdir(parents=True, exist_ok=True)
    VENDOR_PATH.write_text(build_pin_block(args.source_commit) + body, encoding="utf-8")
    print(f"sync-role-register: wrote {VENDOR_PATH} pinned to {args.source_commit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
